// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk1LyoHFyNyP-Pki827EAMw3cRYWP8leo',
    appId: '1:936711119477:web:0c905d945e9f9c90eb0e3c',
    messagingSenderId: '936711119477',
    projectId: 'ecommerce-e-clot',
    authDomain: 'ecommerce-e-clot.firebaseapp.com',
    storageBucket: 'ecommerce-e-clot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANnomzyTbETzlDg2uoJ3NOEWpPzd5uR8s',
    appId: '1:936711119477:android:f7d50c20334bc722eb0e3c',
    messagingSenderId: '936711119477',
    projectId: 'ecommerce-e-clot',
    storageBucket: 'ecommerce-e-clot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPNXzfjkb81NC8wuNpZy3LkaC939oUX98',
    appId: '1:936711119477:ios:3e9abefc27c6852feb0e3c',
    messagingSenderId: '936711119477',
    projectId: 'ecommerce-e-clot',
    storageBucket: 'ecommerce-e-clot.appspot.com',
    iosBundleId: 'com.example.eClot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPNXzfjkb81NC8wuNpZy3LkaC939oUX98',
    appId: '1:936711119477:ios:9fa03ada65b47064eb0e3c',
    messagingSenderId: '936711119477',
    projectId: 'ecommerce-e-clot',
    storageBucket: 'ecommerce-e-clot.appspot.com',
    iosBundleId: 'com.example.eClot.RunnerTests',
  );
}
